<?php 
require_once 'dbh.inc.php';

// Email sending functionality
require './../mailer/mailer.php';
// Ignore mailer deprecated warnings
ob_end_clean();

session_start();

$func = $_POST['function'];

switch ($func) {
    case 'request_passwordReset':
        $email = $_POST['email'];
        $selector = bin2hex(random_bytes(8));
        $token = random_bytes(32);

        $expires = date("Y-m-d H:i:s", strtotime('+2 hours'));

        $url = "https://yelcloud.com/create-new-password.php?selector=$selector&validator=".bin2hex($token);
        
        // Find the person by their email
        $sql = "
            SELECT * FROM users WHERE users.email = '$email'
        ";
        $result = mysqli_query($conn, $sql);
        if ( mysqli_num_rows($result) > 0 ) {
            while ($row = mysqli_fetch_assoc($result)) {
                // Clear all current reset requests for this email
                $sql = "
                    DELETE FROM pwdReset WHERE pwdResetEmail='$email'
                ";
                mysqli_query($conn, $sql);

                $hashedToken = password_hash($token, PASSWORD_DEFAULT);
                $sql = "
                INSERT INTO pwdReset (pwdResetEmail, selector, token, expires) VALUES ('$email', '$selector', '$hashedToken', '$expires');
                ";
                mysqli_query($conn, $sql);

                // Generate Email
                $subject = 'Reset your password for YelCloud';
                $message = "Hello !<br><br>We have received a password reset request. Click on the link below to reset your password: <br><a href='$url'>$url</a> 
                <br><br> If you did not make this request, you can ignore this email.";
                
                $recipient = [$email];

                // OB functions to hide output buffer generated by mailer
                ob_start();
                // Send email
                sendEmail($recipient, $subject, $message);
                ob_end_clean();

                // Generate response
                $response = array();
                $response['status'] = 200;
                $response['message'] = "Reset link has been sent to your email!\n\nIf you don't find, check your junk folder.";
                echo json_encode($response);
            }
        } else {
            // Generate response
            $response = array();
            $response['status'] = 404;
            $response['message'] = 'This email does not exist!';
            echo json_encode($response);
        }
        break;

    case 'new_password':
        $selector = $_POST['selector'];
        $validator = $_POST['validator'];
        $new_password = $_POST['new_password'];
        $confirm_password = $_POST['confirm_password'];
        
        if ($new_password == $confirm_password) {
            $currentTime = date("Y-m-d H:i:s");
            
            $sql = "
                SELECT * FROM pwdReset WHERE selector='$selector'
            ";
            $result = mysqli_query($conn, $sql);
            if ( mysqli_num_rows($result) > 0 ) {
                while ($row = mysqli_fetch_assoc($result)) {
                    $expires = $row['expires'];

                    if ($expires > $currentTime) {
                        
                        if (strlen($new_password) >= 8 ) {
                            
                            // Check for token validity
                            $tokenBin = hex2bin($validator);
                            $tokenCheck = password_verify($tokenBin, $row['token']);

                            if ($tokenCheck === true) {
                                // Check if email exists
                                $sql = "
                                    SELECT * FROM users WHERE email='{$row['pwdResetEmail']}'
                                ";
                                $result = mysqli_query($conn, $sql);
                                if ( mysqli_num_rows($result) > 0 ) {
                                    while ($row = mysqli_fetch_assoc($result)) {
                                        // All checks have passed so change user password
                                        $hashedPwd = password_hash($new_password, PASSWORD_DEFAULT);
                                        $sql = "
                                            UPDATE users SET users.pwd='$hashedPwd' WHERE users.userId={$row['userId']}
                                        ";
                                        mysqli_query($conn, $sql);
                                        
                                        // Clear all current reset requests
                                        $sql = "
                                            DELETE FROM pwdReset WHERE pwdResetEmail='{$row['email']}'
                                        ";
                                        mysqli_query($conn, $sql);

                                        // Generate response
                                        $response = array();
                                        $response['status'] = 200;
                                        $response['message'] = 'Your password has been successfully changed! You can now log in.';
                                        echo json_encode($response);

                                    }
                                } else {
                                    // Generate response
                                    $response = array();
                                    $response['status'] = 400;
                                    $response['message'] = 'This email no longer exists.';
                                    echo json_encode($response);
                                }


                            } else {
                                // Generate response
                                $response = array();
                                $response['status'] = 400;
                                $response['message'] = 'You need to re-submit your reset request.';
                                echo json_encode($response);
                            }

                        } else {
                            // Generate response
                            $response = array();
                            $response['status'] = 400;
                            $response['message'] = 'Your password must be at least 8 characters long!';
                            echo json_encode($response);
                        }

                    } else {
                        // Generate response
                        $response = array();
                        $response['status'] = 400;
                        $response['message'] = 'Your reset link has expired!';
                        echo json_encode($response);
                    }
                }
            } else {
                // Generate response
                $response = array();
                $response['status'] = 400;
                $response['message'] = 'Your reset link is incorrect or no longer exists. Check if you have entered it correctly!';
                echo json_encode($response);
            }
        } else {
            // Generate response
            $response = array();
            $response['status'] = 401;
            $response['message'] = 'Your entered passwords do not match!';
            echo json_encode($response);
        }
        break;

    default:
    //
}

?>
